### ISSUE TITLE
Jena example 19 - Invalid triple store specifications

### ISSUE THREAD

**Issue by Nomeyho** [franzinc/agraph-java-client#6]
Hi,

Running example 19 of the Jena tutorial (inference)
```
mvn exec:java -Dexec.args="19"
```
leads to the following exception:
```
com.franz.agraph.http.exception.AGHttpException: Invalid triple-store specification: <http://admin:*****@localhost:10035/repositories/jenatutorial>{ null}[rdfs++].
```

Did I miss something in the client or server configuration?

My setup:
* client: 3.0.4-SNAPSHOT
* server: AllegoGraph 7.0.2 (free) AWS AMI / local docker image

Thank you,

**Comment by jkftiger348** [comment]
Please send email to support@franz.com so we can help you with this.  Once solved we'll post the solution here.

**Comment by jkftiger348** [comment]
While I haven't been able to reproduce your problem I do have some notes on what it took to get the tutorial to work with the AWS marketplace 7.0.2 edition:

1. you need to define a java-catalog in agraph.cfg.  Something like
<catalog java-catalog>
 main /home/ec2-user/agraph-data/java-catalog
</catalog>

2. sessions will be created and by default they listen on a different port and
one that is likely blocked by the AWS firewall (aka. Security Group).
You have three choices:
a.    put in your agraph.cfg this line
UseMainPortForSessions yes
   and then messages to sessions will be sent through port 10035 which you already
have open in the firewall.

b.  open all ports on the firewall up for incoming requests

c.  in agraph.cfg specify SessionPorts and open up only those ports through the firewall.

3. to tell the tutorial the location and credentials of your server set these environment 
variables:

AGRAPH_HOST
AGRAPH_PORT
AGRAPH_USER
AGRAPH_PASS
AGRAPH_PASSWORD

 the last two have the same value.   Some functions in the tutorial use PASS and others PASSWORD....

**Comment by Nomeyho** [comment]
@jkftiger348 Thanks a lot for your input.

The issue was an invalid character in the password. The `_` character is not accepted by AllegroGraph when it appears in the connection URL:
`<http://test:my_password@0.0.0.0:10035/repositories/jenatutorial>{ null}[rdfs++]`.

We changed the password and everything's working as expected 😄  I'm closing the issue.

**Comment by jkftiger348** [comment]
I'm glad it's working for you but I haven't found a case where the underscore is not accepted as a password character.  In fact when I started an Amazon Marketplace version of AllegroGraph it generated a password with an underscore in it and I was able to run the complete jena tutorial.

I'm not sure what else you changed in order to make this work but please let us know if this happens again in the future.
